### ISSUE TITLE
Is Mapbox etc optional for maps?

### ISSUE THREAD

**Issue by jsodeman** [loftylabs/vue_deckgl#48]
Maybe a dumb question, but all of the map example code uses a Mapbox component and my reason for using Deck.gl is to get away from Mapbox. I have map data in Albers projected geojson. I want to be able to style the layers, show/hide data, zoom, pan etc but I don't need tiling or any basemap data like you'd get from MapBox (streets, building, etc). My base layer is a geojson shape file.

TBH the main deck.gl docs are a bit confusing in this too as it makes it sound you need something to provide a basemap, whether Mapbox or Carto or Google.

**Comment by ahackit** [comment]
@jsodeman If we've done our due diligence (which I just double checked and think our code is correct) you should not need to slot a Mapbox component to use any of the layers with DeckGL. Just make sure you have `:controlMap="false"` prop set on your DeckGL Component. 

As far as which Map implementations are supported, currently the only one implemented/tested is Mapbox.

**Comment by jsodeman** [comment]
Great, thank you. I'm excited to see this project. I wanted to use deck.gl on a project last year and was disappointed at the difficulty of using it in Vue.
